#########################################################################################
# Configurations are based on:
# M. Herman - https://github.com/testdrivenio/spark-docker-swarm
#########################################################################################

version: '3.8'

services:

  master:
    image: ${SPARK_ON_SWARM_REGISTRY}:5000/${SPARK_ON_SWARM_IMAGE_TAG}
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: ${EXTERNAL_IP}
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080

  worker:
    image: ${SPARK_ON_SWARM_REGISTRY}:5000/${SPARK_ON_SWARM_IMAGE_TAG}
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4g
      SPARK_PUBLIC_DNS: ${EXTERNAL_IP}
    depends_on:
      - master
    ports:
      - 8081:8081
